name: "Workflow: PR Lint"

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      - name: Validate Checklists
        uses: open-turo/actions-pr-lint/check-pr-checklist@v1
