name: "Workflow: PR Lint"

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate Checklists
        uses: roryq/checkmate@master
